server:
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: younite666
    #    username: root
    #    password: root
    #    url: jdbc:mysql://localhost:3306/younite?serverTimezone=UTC
    url: jdbc:mysql://younite-database.c7ta6ybbk9nu.ap-northeast-1.rds.amazonaws.com:3306/younite
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

#SWAGER的UI介面功能啟動
springfox:
  documentation:
    swagger-ui:
      enabled: true
#springBoots版本2.X版後就要加上，不然SWAGER會壞掉
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

encryption:
  secretKeyF: YOUNITEDATINGAPPLICATIONFRONTEND
  secretKeyB: 64YOUNITEDATINGAPPLCATIONFORBACKEND

s3:
  region: ap-northeast-1
  accessKeyId: AKIAS73US3WNYZWGIN5E
  accessKeySecret: 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
  bucketName: younite-avatar-bucket
  endpoint: https://younite-avatar-bucket.s3.amazonaws.com


amazon:
  aws:
    access-key-id: AKIAS73US3WNYZWGIN5E
    access-key-secret: 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
  s3:
    default-bucket: younite-avatar-bucket
    region: ap-northeast-1
    dirname: younite-avatar-bucket

cloud:
  aws:
    credentials:
      access-key: AKIAS73US3WNYZWGIN5E
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: younite-avatar-bucket



