spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/younite
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml



